# syntax=docker/dockerfile:1
#FROM python:alpine
FROM python:3.10.1-alpine

RUN apk update && apk upgrade && apk --no-cache add curl && apk --no-cache add gnupg && apk update

# Install pip, git, nano etc
ENV PYTHONUNBUFFERED=1
#RUN apk update && python3 -m ensurepip
#RUN apk update && pip3 install --no-cache --upgrade pip setuptools
RUN apk update && apk add git
RUN apk update && apk add nano
RUN apk update

WORKDIR /tmp
