# syntax=docker/dockerfile:1
FROM hchbprod.azurecr.io/base/kerberos:5.0

RUN apk update && apk upgrade && apk --no-cache add curl && apk --no-cache add gnupg && apk update
 
# Install MS odbc driver 17 & mssql tools
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.8.1.1-1_amd64.apk 
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.8.1.1-1_amd64.apk
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.8.1.1-1_amd64.sig
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.8.1.1-1_amd64.sig
RUN curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import -
RUN apk update && gpg --verify msodbcsql17_17.8.1.1-1_amd64.sig msodbcsql17_17.8.1.1-1_amd64.apk
RUN apk update && gpg --verify mssql-tools_17.8.1.1-1_amd64.sig mssql-tools_17.8.1.1-1_amd64.apk
RUN apk update && apk add --allow-untrusted msodbcsql17_17.8.1.1-1_amd64.apk
RUN apk update && apk add --allow-untrusted mssql-tools_17.8.1.1-1_amd64.apk
RUN ln -sfn /opt/mssql-tools/bin/bcp /usr/bin/bcp && ln -sfn /opt/mssql-tools/bin/sqlcmd /usr/bin/sqlcmd

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk update && apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN apk update && python3 -m ensurepip
RUN apk update && pip3 install --no-cache --upgrade pip setuptools
RUN apk update && apk add unixodbc-dev
RUN apk update && apk add build-base
RUN apk update && apk add python3-dev
RUN apk update && python -m pip install pyodbc
RUN apk update && python -m pip install pytz

# copy unittest_mssql project 
RUN mkdir /opt/unittest_mssql
COPY ./unittest_mssql  /opt/unittest_mssql

#kinit
COPY ./kinit_me.sh /tmp/kinit_me.sh
RUN chmod +x /tmp/kinit_me.sh | /tmp/kinit_me.sh
RUN rm /tmp/kinit_me.sh

