# syntax=docker/dockerfile:1
FROM python:latest
#FROM python:3.10.1-alpine
#FROM python:3.10.1

# Install pip setuptools, git, nano
RUN apt-get update -y && apt-get install -y build-essential
RUN apt-get update -y && apt-get install -y nano

WORKDIR /tmp
