# syntax=docker/dockerfile:1
#FROM python:latest
#FROM python:3.10.1-alpine
#FROM python:3.10.1
FROM mcr.microsoft.com/vscode/devcontainers/anaconda:0-3

#jupyter
EXPOSE 8888

# Install pip setuptools, git, nano
RUN apt-get update -y && apt-get install -y build-essential
RUN apt-get update -y && apt-get install -y nano

# repo specific
RUN apt-get update -y && conda install tabulate natsort


WORKDIR /tmp

#RUN jupyter notebook

# repo specific
RUN git clone https://github.com/hellums/romcom.git